name: Cypress tests

on:
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep '
        required: false
        default: ''
      run:
        required: false
      testomatio:
        required: false
      testomatio_url:
        required: false

jobs:
   build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: cypress-io/github-action@v4
        with:
          command: npx cypress run --env --grep "${{ github.event.inputs.grep }}"
        env: 
          TESTOMATIO: "${{ github.event.inputs.testomatio }}"
          TESTOMATIO_RUN: "${{ github.event.inputs.run }}"
